#!/bin/bash

# Resource List
resources=()

# CNV Namespaces
resources+=(ns/kubevirt ns/cdi)

# VM and VMI
resources+=(vm vmi)

# Run the Collection of Resources using must-gather
for resource in ${resources[@]}; do
    /usr/bin/openshift-must-gather inspect ${resource}
done

# Collect VMs definition
/usr/bin/gather-cnv-vm-definition

exit 0